### ISSUE TITLE
macos 12.4 can not open it

### ISSUE THREAD

**Issue by eryajf** [getseabird/seabird#102]
### Issue description

I installed the ARM version installation package, but there was no response when I clicked on the application icon

### Steps to reproduce

As described in the problem description

### System information

Seabird 0.3.2, MacOS 12.4  on an M1 Pro

**Comment by jgillich** [comment]
Need more info, I don't have access to an ARM Mac. Can you launch it in the terminal?

**Comment by eryajf** [comment]
I tried and it reported an error as follows：

```
$ ./seabird
dyld[189]: Library not loaded: '@executable_path/../libs/libadwaita-1.0.dylib'
  Referenced from: '/Volumes/Seabird/Seabird.app/Contents/MacOS/seabird'
  Reason: tried: '/Volumes/Seabird/Seabird.app/Contents/MacOS/../libs/libadwaita-1.0.dylib' (no such file), '/usr/local/lib/libadwaita-1.0.dylib' (no such file), '/usr/lib/libadwaita-1.0.dylib' (no such file)
[1]    189 abort      ./seabird
```

**Comment by jgillich** [comment]
Launch the script `seabird.sh`

**Comment by eryajf** [comment]
then i get:

```
$ bash seabird.sh
dyld[39132]: Symbol not found: __ZNSt3__122__libcpp_verbose_abortEPKcz
  Referenced from: /Volumes/Seabird/Seabird.app/Contents/MacOS/lib/libvte-2.91-gtk4.0.dylib
  Expected in: /usr/lib/libc++.1.dylib
seabird.sh: line 14: 39132 Abort trap: 6           "$LAUNCH_DIR/seabird"
```

**Comment by air3ijai** [comment]
Did a check on M3 / MacOS 14.5
1. Install latest [seabird_darwin_arm64.dmg](https://github.com/getseabird/seabird/releases/tag/v0.3.2)
2. `cd /Applications/Seabird.app/Contents/MacOS`
3. `bash seabird.sh`
4. App is running

<img width="1151" alt="Screenshot 2024-06-21 at 13 07 27" src="https://github.com/getseabird/seabird/assets/88528265/048de863-6394-4283-904e-eccdab689f84">

<img width="590" alt="Screenshot 2024-06-21 at 13 07 48" src="https://github.com/getseabird/seabird/assets/88528265/4aa9c03b-760f-481a-8c69-230fa5b6e40e">

**Comment by jgillich** [comment]
It looks like the vte from Homebrew does not work on macOS 12.4. macOS 14 is the only ARM runner GitHub offers, so we can't build on an older version either. I don't think we can support macOS 12 at this time.
