### ISSUE TITLE
After statefulSet update old pods not removed

### ISSUE THREAD

**Issue by d-enk** [getseabird/seabird#107]
### Issue description

![image](https://github.com/getseabird/seabird/assets/43112758/f53fdab8-f797-4a42-b8e5-e6f57f973566)

### Steps to reproduce

Update statefulSet with RollingUpdate updateStrategy

### System information

Seabird v0.3.2

**Comment by jgillich** [comment]
Can't reproduce, when I change the image, the old pods are removed. Changing the update strategy does not trigger new pods to be created. If this is still an issue for you, please add more detailed reproduction steps.
