### ISSUE TITLE
Screenshot size

### ISSUE THREAD

**Issue by bertob** [getseabird/seabird#16]
Appdata screenshots [should ideally be smaller than 1000x700 pixels](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), otherwise the UI is hard to see on the thumbnails in app stores. The height is particularly important for this since that's usually what causes it to be scaled.

This is becoming more important now because we're planning to use app screenshots for "featured" banners on Flathub :)

**Comment by jgillich** [comment]
This one should be better https://github.com/getseabird/getseabird.github.io/commit/29a2eeb226208dda8eb91890358ddabf28963e51

Still a bit too wide, fitting the three column layout into 1000px is tough. But the height's nearly 700px now

**Comment by bertob** [comment]
Thanks! For next time, I think the right pane could be quite a bit narrower before it starts folding, that would allow the window to be narrower and still show all three panes.

**Comment by jgillich** [comment]
Possibly, but I need the right pane to expand for the source vie and, if I drag the window any narrower it doesn't fit the middle pane anymore. It can probably be solved in GTK showehow..but I don't know how yet. :smile:

**Comment by jgillich** [comment]
Managed to reduce the min width of the right pane a bit https://github.com/getseabird/getseabird.github.io/commit/76ad2180687613380962ffd589c07d2fc495a9de

I don't think there's more I can do without removing columns. We'll probably make them configurable in the future, but I think this is good enough for now. Look and feel on real-world displays is more important than screenshots imo

**Comment by bertob** [comment]
FYI, if you have questions about GTK stuff like this, the #libadwaita room on Matrix is usually a good place to ask :)
