### ISSUE TITLE
Pods logs - add word wrap

### ISSUE THREAD

**Issue by pcfighter** [getseabird/seabird#20]
Hello, nice project! UX very similar to Openshift, which is very good decision.

It would be beneficial to introduce word wrap option for logs, so scrolling would not be needed:

![image](https://github.com/getseabird/seabird/assets/769478/210b57ce-bfe0-43b8-8099-95964a153cee)

Thank you for your hard work

**Comment by jgillich** [comment]
Added in 3d039f1848914d32ad1778bfb6bc8eaac48217dd

![Screenshot from 2024-02-01 22-33-05](https://github.com/getseabird/seabird/assets/347965/10cc2422-7878-40e5-8c5c-52da10a86044)
