### ISSUE TITLE
Add flatpak and flathub

### ISSUE THREAD

**Issue by marcinjahn** [getseabird/seabird#3]
I think it'd be much easier for new users to find this app if it was published on flathub. During its early stages, it'd probably make sense to go with flathub-beta.

**Comment by jgillich** [comment]
Flatpak bundles are now attached to releases. Publishing to Flathub is a bit difficult though since they don't allow network access during builds. We'll have to wait until flatpak-builder-tools is updated with a solution that works with go modules.

**Comment by jgillich** [comment]
https://flathub.org/apps/dev.skynomads.Seabird
