### ISSUE TITLE
Hidden directories (and files) are not shown in filepicker on Windows

### ISSUE THREAD

**Issue by mvarendorff** [getseabird/seabird#38]
### Issue description

Testing out Seabird moving on from Lens, I wanted to select one of the kubeconfigs saved under the Lens app-directory. On Windows, this is under a (by default) hidden folder in the user directory. In the filepicker, this folder (`AppData`) is not shown.

### Steps to reproduce

1. Launch Seabird, select New Cluster
2. Load Kubeconfig
3. Frantically (and desperately) try navigating to `C:\Users\<user>\AppData\Roaming\OpenLens\kubeconfigs`

### System information

Seabird v0.1.0, Windows 10, x64

**Comment by jgillich** [comment]
You can right click and enable "Show Hidden Files"

![Screenshot from 2024-02-14 15-07-43](https://github.com/getseabird/seabird/assets/347965/de178f48-11d3-46b1-afb9-c5f33d2ee48b)

However, it is actually supposed to use the native file picker. I'll fix that

**Comment by mvarendorff** [comment]
Oh boy, I didn't even fathom right-clicking because I am so used to everything just being there, my apologies! Would you rather I close this (since the actual issue is not really one) or keep it open for the native file picker?
