### ISSUE TITLE
Error under WSL (debian)

### ISSUE THREAD

**Issue by kgelinas** [getseabird/seabird#39]
### Issue description

After installing with flatpack the error
MESA: error: ZINK: Failed to choose pdev
LibEGL warning: egl: failed to create dri2 screen.
When i try to pick from my kube config le picker freeze after confirm

### Steps to reproduce

Basic installation of debian wsl image
Installing flatpack
Install seabird flatpack package
Run the package

### System information

Debian WSL

**Comment by jgillich** [comment]
Do other GTK4 apps installed via Flatpak work? What's the full console output? This might be something WSL-specific, we have a Windows version so perhaps you could use that?

**Comment by jgillich** [comment]
So I've tested this and it works fine for me, but you need to restart your shell after installing flatpak or the file picker doesn't work. But importing a kubeconfig and connecting to a different vm can be tricky. Therefore I don't recommend this, it's easier to use the Windows binary.
