### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by lucsoft** [getseabird/seabird#4]

**Comment by jgillich** [comment]
Would be great if Mac users could help with setting up a CI pipeline. I don't own any Apple  devices.

**Comment by lucsoft** [comment]
@jgillich sorry didn't look at the code but is there already a macOS build target?

**Comment by jgillich** [comment]
There's no platform-specific code, `go build` what you'd use to build. Also need to have the [dependencies](https://github.com/getseabird/seabird/blob/7806be722602503cbb04e9a47db4f20475e095e6/.github/workflows/release.yaml#L24). For distribution, we'll probably have to bundle them along with some other files like icons.

**Comment by air3ijai** [comment]
I'm experimenting with the following configuration

**`.goreleaser.darwin.yaml`**
```yaml
version: 1

before:
  hooks:
    - go generate ./...

builds:
  - flags:
      -trimpath
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
```

**`release.yaml`**
```yaml
  darwin:
    # needs: goreleaser
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew --version
      - name: Install dependencies
        run: |
          brew install gtk4 pkg-config gobject-introspection gtksourceview5 libadwaita
      - name: Build
        run: |
          go run github.com/goreleaser/goreleaser@latest build -f .goreleaser.darwin.yaml --single-target --snapshot
          ls -la dist
```

And I get the following error at the build step
<img width="1100" alt="Screenshot 2024-01-27 at 22 47 52" src="https://github.com/getseabird/seabird/assets/88528265/48951589-a8b5-42e2-9776-032a53b5ff70">

**Comment by air3ijai** [comment]
And on local ARM VM it works fine, but why do we get an additional console windows at run?
```
goreleaser build -f .goreleaser.darwin.yaml --clean --single-target --snapshot
```
Is there a way to use something like we use for Windows builds?
```
    ldflags:
      - -H=windowsgui
```

<img width="998" alt="Screenshot 2024-01-27 at 23 14 06" src="https://github.com/getseabird/seabird/assets/88528265/cca90824-a2a0-492e-8bc4-fc93e9550d2a">

**Comment by air3ijai** [comment]
GitHub Actions build was fixed by adding a step
```yaml
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
```

**Comment by air3ijai** [comment]
I've tried to copy all dependencies to be able to run app in a portable mode, but something is not working
1. We need to copy a lot of libraries and shared files and part of the libraries were defined manually(is there another way to do that?)
2. In order to use libraries from a binary folder it is required to define `export DYLD_LIBRARY_PATH=.` - otherwise, app will try to find libraries in a different location 
    ```
    dyld[83960]: Library not loaded: /opt/homebrew/opt/libadwaita/lib/libadwaita-1.0.dylib
    ```
3. We also need to define `export GSETTINGS_SCHEMA_DIR="share/glib-2.0/schemas"` - otherwise, we will get the error
     ```
      2024/01/28 12:24:21 Critical: GLib-GIO: g_settings_schema_source_lookup: assertion 'source != NULL' failed
     ```

After all that, app is running but not all assets are loaded - should we copy [icon](../tree/main/icon) folder and if yes, where?

<details>
<summary>screenshots</summary>

### On builder
<img width="599" alt="Screenshot 2024-01-28 at 12 34 43" src="https://github.com/getseabird/seabird/assets/88528265/c3bee08e-526e-4e6b-a58c-efaf61c4c1ae">

### On end system
<img width="601" alt="Screenshot 2024-01-28 at 12 33 18" src="https://github.com/getseabird/seabird/assets/88528265/47ce480d-4310-4fc2-85d1-c38ec097b90c">
</details>



<details>

<summary>.goreleaser.darwin.yaml</summary>

```yaml
version: 1

before:
  hooks:
    - go generate ./...

builds:
  - flags:
      -trimpath
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
```
</details>

<details>
<summary>release.yaml</summary>

```yaml
  darwin:
    # needs: goreleaser
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew --version

      - name: Install dependencies
        run: |
          brew install gtk4 pkg-config gobject-introspection gtksourceview5 libadwaita hicolor-icon-theme adwaita-icon-theme

      - name: Build
        run: |
          # Build
          go run github.com/goreleaser/goreleaser@latest build -f .goreleaser.darwin.yaml --single-target --snapshot

          # Folders
          dist_folder=dist/seabird_darwin_amd64_v1
          brew_prefix=$(brew --prefix)
          mkdir -p $dist_folder/lib/gdk-pixbuf-2.0
          mkdir -p $dist_folder/share/glib-2.0/schemas
          mkdir -p $dist_folder/share/icons

          # Files
          cp README.md LICENSE $dist_folder
          # libs
          otool -L $dist_folder/seabird | awk -v pat="$brew_prefix" '$0~pat {print $1}' | xargs -I '{}' cp '{}' $dist_folder
          for lib in \
            libfribidi.0.dylib \
            libgmodule-2.0.0.dylib \
            libpangoft2-1.0.0.dylib \
            libfreetype.6.dylib \
            libpng16.16.dylib \
            libappstream.5.dylib \
            libepoxy.0.dylib \
            libfontconfig.1.dylib \
            libgraphite2.3.dylib \
            libjpeg.8.dylib \
            libtiff.6.dylib \
            libharfbuzz-gobject.0.dylib \
            libX11.6.dylib \
            libxmlb.2.dylib \
            libcairo-script-interpreter.2.dylib \
            libXext.6.dylib \
            libyaml-0.2.dylib \
            libXrender.1.dylib \
            libxcb.1.dylib \
            libxcb-render.0.dylib \
            libxcb-shm.0.dylib \
            libpixman-1.0.dylib \
            libXau.6.dylib \
            liblzo2.2.dylib \
            libXdmcp.6.dylib \
          ; do
            cp -f $brew_prefix/lib/$lib $dist_folder
          done
          
          # ./lib/gdk-pixbuf-2.0
          cp -r $brew_prefix/opt/gdk-pixbuf/lib/gdk-pixbuf-2.0 $dist_folder/lib
          # ./share/glib-2.0/schemas
          cp -r $brew_prefix/share/glib-2.0/schemas $dist_folder/share/glib-2.0
          # ./share/gtksourceview-5
          cp -r $brew_prefix/opt/gtksourceview5/share/gtksourceview-5 $dist_folder/share/gtksourceview-5 
          # ./share/gtk-4.0
          cp -r $brew_prefix/opt/gtk4/share/gtk-4.0 $dist_folder/share
          # ./share/icons
          cp -r $brew_prefix/opt/adwaita-icon-theme/share/icons/Adwaita $dist_folder/share/icons
          cp -r $brew_prefix/share/icons/hicolor $dist_folder/share/icons

          # Archive
          tar cvzf seabird_darwin_amd64.tar.gz -C $dist_folder .

      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: seabird_darwin_amd64.tar.gz
          tag: ${{ github.ref }}
```
</details>

**Comment by jgillich** [comment]
You don't need to copy the icons folder, it's embedded at build time. if the custom icons don't load, you are probably missing librsvg or gdk-pixbuf loaders (https://github.com/getseabird/seabird/commit/d9976f4941364d88d45f8aaf5f45c6f01317e7f4)

**Comment by air3ijai** [comment]
Found a new directory which contains an svg loader as well
```
88896 Jan 28 13:21 libpixbufloader-ani.so
86576 Jan 28 13:21 libpixbufloader-bmp.so
90464 Jan 28 13:21 libpixbufloader-gif.so
70528 Jan 28 13:21 libpixbufloader-icns.s
87520 Jan 28 13:21 libpixbufloader-ico.so
86352 Jan 28 13:21 libpixbufloader-pnm.so
86624 Jan 28 13:21 libpixbufloader-qtif.s
 4248 Jan 28 13:21 libpixbufloader-svg.a
85840 Jan 28 13:21 libpixbufloader-svg.so
87664 Jan 28 13:21 libpixbufloader-tga.so
88512 Jan 28 13:21 libpixbufloader-tiff.s
87008 Jan 28 13:21 libpixbufloader-xbm.so
88304 Jan 28 13:21 libpixbufloader-xpm.so
```
and copied
```
5531888 Jan 28 13:31 librsvg-2.2.dylib
5531888 Jan 28 13:31 librsvg-2.dylib
```

Set a variable `export GDK_PIXBUF_MODULEDIR="./lib/gdk-pixbuf-2.0/2.10.0/loaders"`

But still same result.

**Comment by jgillich** [comment]
Found this article that looks helpful: https://www.datatable.online/en/blog/004-how-to-deploy-gtk-app-on-mac.html#create-app-package-dmg

Their launcher script also sets `GDK_PIXBUF_MODULE_FILE="./gdk-pixbuf-2.0/2.10.0/loaders.cache"`, perhaps that's what you're missing

**Comment by air3ijai** [comment]
These steps solved the issue with the icons
1. In `lib/gdk-pixbuf-2.0/2.10.0/loaders.cache` it is required to update paths reference to `.so` files
    ```shell
     sed -i '' "s|$brew_prefix/||" $dist_folder/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
     ```
2. Define 2 variables
    ```
    GDK_PIXBUF_MODULEDIR=lib/gdk-pixbuf-2.0
    GDK_PIXBUF_MODULE_FILE=lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
    ```
3. Copy `librsvg-2.2.dylib`

**Comment by air3ijai** [comment]
Copy/paste for local builds on ARM

<details>
<summary>details</summary>

### Install brew
```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

### Install dependencies
```shell
brew install gtk4 pkg-config gobject-introspection gtksourceview5 libadwaita hicolor-icon-theme adwaita-icon-theme
```

### Build
```shell
go run github.com/goreleaser/goreleaser@latest build -f .goreleaser.darwin.yaml --clean --single-target --snapshot
```

### Create an archive
```shell
# Folders
dist_folder=dist/seabird_darwin_`uname -m`
lib_folder=$dist_folder/lib
share_folder=$dist_folder/share
brew_prefix=$(brew --prefix)
mkdir -p $lib_folder/gdk-pixbuf-2.0
mkdir -p $share_folder/glib-2.0/schemas
mkdir -p $share_folder/icons

# Files
cp README.md LICENSE $dist_folder

# libs
otool -L $dist_folder/seabird | awk -v pat="$brew_prefix" '$0~pat {print $1}' | xargs -I '{}' cp '{}' $lib_folder

for lib in \
  libfribidi.0.dylib \
  libgmodule-2.0.0.dylib \
  libpangoft2-1.0.0.dylib \
  libfreetype.6.dylib \
  libpng16.16.dylib \
  libappstream.5.dylib \
  libepoxy.0.dylib \
  libfontconfig.1.dylib \
  libgraphite2.3.dylib \
  libjpeg.8.dylib \
  libtiff.6.dylib \
  libharfbuzz-gobject.0.dylib \
  libX11.6.dylib \
  libxmlb.2.dylib \
  libcairo-script-interpreter.2.dylib \
  libXext.6.dylib \
  libyaml-0.2.dylib \
  libXrender.1.dylib \
  libxcb.1.dylib \
  libxcb-render.0.dylib \
  libxcb-shm.0.dylib \
  libpixman-1.0.dylib \
  libXau.6.dylib \
  liblzo2.2.dylib \
  libXdmcp.6.dylib \
  librsvg-2.2.dylib \
; do
  cp -f $brew_prefix/lib/$lib $lib_folder
done

# ./lib/gdk-pixbuf-2.0
cp -r $brew_prefix/lib/gdk-pixbuf-2.0 $lib_folder
sed -i '' "s|$brew_prefix/||" $lib_folder/gdk-pixbuf-2.0/2.10.0/loaders.cache
# ./share/glib-2.0/schemas
cp -r $brew_prefix/share/glib-2.0/schemas $share_folder/glib-2.0
# ./share/gtksourceview-5
cp -r $brew_prefix/opt/gtksourceview5/share/gtksourceview-5 $share_folder/gtksourceview-5 
# ./share/gtk-4.0
cp -r $brew_prefix/opt/gtk4/share/gtk-4.0 $share_folder
# ./share/icons
cp -r $brew_prefix/opt/adwaita-icon-theme/share/icons/Adwaita $share_folder/icons
cp -r $brew_prefix/share/icons/hicolor $share_folder/icons

# Runner file
launcher_file=$dist_folder/seabird_launcher.sh
echo 'cd "$(dirname "$0")"' >>$launcher_file
echo 'LAUNCH_DIR="$(pwd)"' >>$launcher_file
echo 'export DYLD_LIBRARY_PATH="$LAUNCH_DIR/lib"' >>$launcher_file
echo 'export GSETTINGS_SCHEMA_DIR="$LAUNCH_DIR/share/glib-2.0/schemas"' >>$launcher_file
echo 'export GDK_PIXBUF_MODULEDIR="$LAUNCH_DIR/lib/gdk-pixbuf-2.0"' >>$launcher_file
echo 'export GDK_PIXBUF_MODULE_FILE="$LAUNCH_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"' >>$launcher_file
echo '"$LAUNCH_DIR/seabird"'
chmod 777 $launcher_file

# Archive
tar cvzf seabird_darwin_`uname -m`.tar.gz -C $dist_folder .
```
</details>

**Comment by air3ijai** [comment]
@jgillich, we miss one line from the [`shell script`](https://github.com/getseabird/seabird/commit/aa773baebeadf044002e27163d8c97321e29f963#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR224)

```shell
"$LAUNCH_DIR/seabird"
```

Should be added to the [`build/darwin/seabird.sh`](https://github.com/getseabird/seabird/blob/main/build/darwin/seabird.sh).

**Comment by jgillich** [comment]
oops, fixed

**Comment by lucsoft** [comment]
if i run the file from the release i get "cannot execute binary file"

**Comment by air3ijai** [comment]
What is your macOS architecture?

**Comment by air3ijai** [comment]
Is there a way to implement that on amd64?

macOS ARM runners a part of the [Large runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners) and available for Organizations with GitHub Team plan - `4 $/m per user`.
Also, they will always be billed at the [per-minute rate](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

But looks like we have a free option - [500 min/m](https://github.com/actions/runner-images/issues/8439#issuecomment-1892479838) using non-github runners.

**Comment by air3ijai** [comment]
Did some experiments with the [FlyCI](https://www.flyci.net/)

<details>
<summary>build/darwin/.goreleaser.yaml</summary>

```yaml
version: 1

before:
  hooks:
    - go generate ./...

builds:
  - flags:
      -trimpath
    # goos:
    #   - darwin
    # goarch:
    #   - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
```
</details>

<details>
<summary>.github/workflows/release.yaml</summary>

```yaml
name: release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  darwin:
    runs-on: flyci-macos-large-latest-m1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: |
          brew install gtk4 pkg-config gobject-introspection gtksourceview5 libadwaita hicolor-icon-theme adwaita-icon-theme
      - name: Build
        run: |
          go run github.com/goreleaser/goreleaser@latest build -f build/darwin/.goreleaser.yaml --single-target --snapshot

          dist=dist/seabird_darwin_arm64
          brew_prefix=$(brew --prefix)
          mkdir -p $dist/lib/gdk-pixbuf-2.0 $dist/share/glib-2.0/schemas $dist/share/icons

          cp README.md LICENSE build/darwin/seabird.sh $dist
          otool -L $dist/seabird | awk -v pat="$brew_prefix" '$0~pat {print $1}' | xargs -I '{}' cp '{}' $dist/lib

          for lib in \
            libfribidi.0.dylib \
            libgmodule-2.0.0.dylib \
            libpangoft2-1.0.0.dylib \
            libfreetype.6.dylib \
            libpng16.16.dylib \
            libappstream.5.dylib \
            libepoxy.0.dylib \
            libfontconfig.1.dylib \
            libgraphite2.3.dylib \
            libjpeg.8.dylib \
            libtiff.6.dylib \
            libharfbuzz-gobject.0.dylib \
            libX11.6.dylib \
            libxmlb.2.dylib \
            libcairo-script-interpreter.2.dylib \
            libXext.6.dylib \
            libyaml-0.2.dylib \
            libXrender.1.dylib \
            libxcb.1.dylib \
            libxcb-render.0.dylib \
            libxcb-shm.0.dylib \
            libpixman-1.0.dylib \
            libXau.6.dylib \
            liblzo2.2.dylib \
            libXdmcp.6.dylib \
            librsvg-2.2.dylib \
          ; do
            cp -f $brew_prefix/lib/$lib $dist/lib
          done

          cp -r $brew_prefix/lib/gdk-pixbuf-2.0 $dist/lib
          sed -i '' "s|$brew_prefix/||" $dist/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
          cp -r $brew_prefix/share/glib-2.0/schemas $dist/share/glib-2.0
          cp -r $brew_prefix/opt/gtksourceview5/share/gtksourceview-5 $dist/share/gtksourceview-5 
          cp -r $brew_prefix/opt/gtk4/share/gtk-4.0 $dist/share
          cp -r $brew_prefix/share/icons/hicolor $brew_prefix/opt/adwaita-icon-theme/share/icons/Adwaita $dist/share/icons

          tar cvzf seabird_darwin_arm64.tar.gz -C $dist .
      - uses: actions/upload-artifact@v4
        with:
          name: darwin
          path: seabird_darwin_arm64.tar.gz
          if-no-files-found: error
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: seabird_darwin_arm64.tar.gz
          tag: ${{ github.ref }}
```
</details>

1. File `.goreleaser.yaml` probably can be generalized
2. We should have a separate workflow for macOS ARM builds and only for releases to fit the limit. And we also may consider to use [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) for macOS releases.
3. We can use almost same code for `amd64` and `arm64` but should update all occurrences (`uname -m`) and [Why is there a _v1 suffix on amd64 builds?](https://goreleaser.com/customization/builds/#why-is-there-a-_v1-suffix-on-amd64-builds)
    ```diff
    + dist=dist/seabird_darwin_arm64
    - dist=dist/seabird_darwin_amd64_v1

    - seabird_darwin_amd64.tar.gz
    + seabird_darwin_arm64.tar.gz
    ```
4. Build was created but at run macOS didn't permit me to run it and asked permissions for every library - [Apple can’t check app for malicious software](https://support.apple.com/en-md/guide/mac-help/mchleab3a043/mac).
    Is there a way to bypass that?
    <img width="254" alt="Screenshot 2024-02-01 at 12 41 27" src="https://github.com/getseabird/seabird/assets/88528265/d35d56d0-75cb-4c92-b0c4-bf101a2ceaea">

**Comment by jgillich** [comment]
There is a M1 runner in beta: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

But the arm64 build should work with rosetta. Are you sure you didn't accidentally download the linux build? :smile:

**Comment by jgillich** [comment]
Goreleaser also supports universal binaries: https://goreleaser.com/customization/universalbinaries/

But that requires cross-compilation. Not idea how to set that up on Mac, Google didn't bring up much

**Comment by air3ijai** [comment]
> There is a M1 runner in beta: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Oh, that's a good news - just did a test and it works on macOS arm, but as it was mentioned we need to disable app verification
```shell
sudo spctl --master-disable
```


> But the amd64 build should work with rosetta. Are you sure you didn't accidentally download the linux build? 😄

That issue was mentioned in the [initial PR](10) and I was not able to check amd64 builds on arm.


> Goreleaser also supports universal binaries: https://goreleaser.com/customization/universalbinaries/
> But that requires cross-compilation. Not idea how to set that up on Mac, Google didn't bring up much

That didn't work during initial PR implementation because missed components.

**Comment by jgillich** [comment]
Re the crash, try setting XDG_DATA_DIRS to `$(pwd)/share`.

**Comment by air3ijai** [comment]
That fixed the issue, thanks!

Added to the PR and checked the artifact.

**Comment by jgillich** [comment]
I set up OSX in a VM and the binary doesn't work for me either, getting "exec format error" on x84. Very strange :thinking:

**Comment by jgillich** [comment]
zip produces a valid binary whereas tar does not. bsd tar produces a corrupt archive. Amazing  https://github.com/actions/runner-images/issues/2619

**Comment by air3ijai** [comment]
Yeah, good catch :)

Did a check of the [one of the latest builds](https://github.com/getseabird/seabird/actions/runs/7752426694) with gnu tar
1. x64 binary is running on arm with a missing library (`libzstd.1.dylib`), but at least no `exec format error` anymore
2. arm binary runs as expected on arm
3. `arm dmg` does not work on arm - will check latests builds, we can see that at installation step and at run
     <img width="787" alt="Screenshot 2024-02-02 at 09 42 03" src="https://github.com/getseabird/seabird/assets/88528265/11d23215-3904-4013-bd08-03e912dd2417">
     <img width="249" alt="Screenshot 2024-02-02 at 09 42 23" src="https://github.com/getseabird/seabird/assets/88528265/daabac57-fd1a-4160-afeb-c539d24c8fda">

**Comment by jgillich** [comment]
The x64 build is incredibly flaky too
```
hdiutil: create failed - Resource busy
```
Apparently it's because OSX detects the dmg as a virus or something, happens to a lot of people on GH actions

**Comment by air3ijai** [comment]
Also discussed on the https://github.com/create-dmg/create-dmg/issues/143 and for M1 (arm) as well.

**Comment by jgillich** [comment]
Yea, killing XProtect doesn't seem to work very well. Going to have it retry until it succeeds. Total BS

**Comment by air3ijai** [comment]
Builds with the [dylibbundler](https://github.com/getseabird/seabird/commit/364715ee59f55cf59ba65c32ebf96854daa3eab0) return me to the [p.3](#issuecomment-1913580130)
```shell
# dm from mentioned commit
ls /Applications/Seabird.app/Contents/MacOS/lib | grep librsvg-2.2.dylib

# dmg from latest release
ls /Volumes/Seabird/Seabird.app/Contents/MacOS/lib | grep librsvg-2.2.dylib
librsvg-2.2.dylib
```
<img width="592" alt="Screenshot 2024-02-02 at 11 54 22" src="https://github.com/getseabird/seabird/assets/88528265/4aa4efbc-c1cb-4492-8da6-eb7bdc6162b2">

**Comment by air3ijai** [comment]
On `arm` dmg checks
- amd64 ✅ 
- arm64 ✅

**Comment by ajax-bychenok-y** [comment]
Is it possible to increase app fonts on Mac?
