### ISSUE TITLE
Unable to connect to Azure AKS clusters

### ISSUE THREAD

**Issue by opsydev** [getseabird/seabird#50]
### Issue description

When trying to connect to an AKS cluster using kubelogin ExecProvider Seabird cannot find the the executable.

![image](https://github.com/getseabird/seabird/assets/3767518/03067bbf-a8e1-451e-ad6a-41aa6ab2205c)

### Steps to reproduce

1. Install kubeconfig to a directory in the path. (/usr/local/bin) in my case
2. Install latest Seabird (0.1.2)
3. Download latest aks kubeconfig using az-cli
4. Load Config file in Seabird and try to connect.

### System information

Seabird 0.1.2, Pop_OS! 22.04 with Linux kernel 6.6.10

**Comment by jgillich** [comment]
Are you using the Flatpak? It doesn't have access to system directories. Put the binary in your home dir.

**Comment by opsydev** [comment]
Yes! I am on flatpak and that was it. Thanks for the quick reply. I totally forgot about flatpak permissions. :sweat_smile:
