### ISSUE TITLE
gke-gcloud-auth-plugin error when connecting

### ISSUE THREAD

**Issue by marcinjahn** [getseabird/seabird#59]
### Issue description

After selecting a context from my kubeconfig file, I get the following error:

![Screenshot from 2024-03-03 13-36-30-obfuscated](https://github.com/getseabird/seabird/assets/10273406/9c3514e9-86b1-48c3-94da-e4ee8c562013)

I do have `gke-gcloud-auth-plugin` installed, and it does work via `kubectl`. 

### Steps to reproduce

Try to add a GKE-backed kubernetes cluster to the app

### System information

seabird 0.1.2 from flatpak (Flathub)

**Comment by jgillich** [comment]
The Flatpak cannot access system paths, you need to have the binary in your home directory.

**Comment by marcinjahn** [comment]
Right, or probably the user could add path to the binary to the sandox (e.g. via flatseal). I think it'd be useful to add that information to `README.md`.

**Comment by jgillich** [comment]
Readme probably isn't good enough, this is a common issue on both Linux and macOS. 1bb8101c92855284ad431196d4a455b4cf32000d adds a custom error message with a link to the docs

**Comment by jomakori** [comment]
This is still an issue, I have attempted allowing permissions via flatseal to all system files including `/usr/bin` where its hosted or by copying `gke-gcloud-auth-plugin` to `~/.local/bin` to no avail, still getting the message that its unable to detect the plugin 😒
