### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by cyppe** [getseabird/seabird#61]
### Issue description

Not sure how to connect.

I select by kubeconfig (OSX) file.

And it loads the information.

But then It says:

<img width="299" alt="image" src="https://github.com/getseabird/seabird/assets/591720/2831f6f6-3e6e-413a-a82a-e9225fde6cbf">

But I do have it?

❯ gke-gcloud-auth-plugin --version

Kubernetes v1.28.2-alpha+58ec6ae34b7dcd9699b37986ccb12b3bbac88f00

Its not possible to edit the field of the command to run, I can click cross to delete current value (gke-gcloud-auth-plugin) but cannot paste new value to try to use full path to command in case it does not read correct $PATH env.

### Steps to reproduce

N/A

### System information

OSX. Latest version (

**Comment by aexvir** [comment]
close the app, reopen, and it will work
at least that's what happened to me as well, the first time it complained about the auth plugin being missing but then it worked just fine

**Comment by jgillich** [comment]
You must set your `PATH` variable with launchctl, shell configuration files do not apply to GUI apps on darwin. You can also hard-code the path in the kubeconfig, we currently don't support editing it within the settings

**Comment by jgillich** [comment]
Can you guys confirm that adding the path in a new file in `/etc/paths.d` works? It's difficult to find definitive information, and I'm not a macOS user. [This page](https://getseabird.github.io/docs/credential-plugins/) is linked by a new error message, I hope that makes it a littler easier to understand what's wrong
