### ISSUE TITLE
Live updates

### ISSUE THREAD

**Issue by UltraSive** [getseabird/seabird#7]
Often I change the state of my cluster and when looking back at the same resource type it will not be able to automatically reload. Most of the time I just switch to another page before going back. Thinking about making this feature my first pull request if you don't have the time to implement it.

**Comment by jgillich** [comment]
Reload shouldn't be necessary since we can use watcher. Already got a prototype working, will be added soon

**Comment by jgillich** [comment]
PR is up if you'd like to try.
