### ISSUE TITLE
Fractional Scaling on GNOME Wayland causes display bugs

### ISSUE THREAD

**Issue by CrimsonFez** [getseabird/seabird#78]
### Issue description

With 100% Scaling
![image](https://github.com/getseabird/seabird/assets/46582994/5f98db26-97c3-45a6-94bd-b9d992726cad)

With 150% Scaling
![image](https://github.com/getseabird/seabird/assets/46582994/f6de7774-1477-430f-9c2f-d416a160f1df)

### Steps to reproduce

Install from Flatpak and use with Fractional Scaling Enabled on GNOME Wayland Session

### System information

v0.3.0, Fedora 39, x86_64, Wayland Session

**Comment by jgillich** [comment]
Try this build https://github.com/flathub/dev.skynomads.Seabird/pull/15

**Comment by CrimsonFez** [comment]
no dice

**Comment by jgillich** [comment]
I have tested fractional scaling on GNOME 46 and it appears to work fine now
