### ISSUE TITLE
Better identify pods vs jobs

### ISSUE THREAD

**Issue by kallisti5** [getseabird/seabird#88]
### Summary

There's no real identification of pods vs job in the UI. It would be nice to indicate pods started by a job somehow.

### Motivation

Showing clear run-once jobs vs continuing to run pods helps clarify what's going on to users. In the example below, nothing indicates the highlighted pods are job spawned.

![pods](https://github.com/getseabird/seabird/assets/100110/f380cbab-d288-4e90-8502-e5119c273fb2)

### Proposal

Kubernetes does track if pods are spawned by jobs:

```
kubectl describe pod/gerrit-github-sync-28588020-xbcrs
Name:             gerrit-github-sync-28588020-xbcrs
Namespace:        default
Priority:         0
Service Account:  default
Node:             XXXXXXXXX
Start Time:       Thu, 09 May 2024 14:00:00 -0500
Labels:           batch.kubernetes.io/controller-uid=XXXXXX
                  batch.kubernetes.io/job-name=gerrit-github-sync-28588020
                  controller-uid=62cbef6d-4306-4838-b67e-413f7f9d4da4
                  job-name=gerrit-github-sync-28588020
Annotations:      <none>
Status:           Succeeded
```

Providing some indication of a once-run job pod (maybe linking to the job) would be useful.

**Comment by jgillich** [comment]
With b44609f7329b36c4832343e3434cf88903440bb1, completed containers now get a blue checkmark.

![Screenshot from 2024-07-09 22-36-10](https://github.com/getseabird/seabird/assets/347965/65cd5cf9-9c96-4b01-bdbf-7b951dad137b)

Probably good enough? Owner could be a column to add, but first we need configurable columns as I don't think it needs to be shown by default.
