### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by ogarcia** [getseabird/seabird#9]
I think that since version 0.0.7 I cannot build the binary.

What I do:
1. I download the code in tar.gz from a tag (e.g. [0.0.14](https://github.com/getseabird/seabird/archive/refs/tags/v0.0.14.tar.gz))
2. I unzip the tar.gz and enter the directory of the code
3. I run the following
    ```
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
    _LDFLAGS="-X main.version=${pkgver} -X main.branch=master -linkmode=external -extldflags ${LDFLAGS}"
    go build -o seabird -ldflags="${_LDFLAGS}" "."
    ```
4. I get the following error:
    ```
    icon/icon.go:12:12: pattern icon.gresource: no matching files found
    ```

I don't know if you can guide me. Compiling the code this way is because I am [maintaining the package on Arch Linux AUR](https://aur.archlinux.org/packages/seabird).

**Comment by jgillich** [comment]
Hi, you need to run `go generate ./...` to generate the resource file, and need to have `glib-compile-resources` installed (seems to be in glib2 on Arch so you probably already have it).

**Comment by ogarcia** [comment]
Yes, adding `go generate ./...` did the trick. :smiley:

Now [package is updated to latest version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=seabird). Thanks!!!

**Comment by jgillich** [comment]
Heads up, 0.1 needs vte

**Comment by jgillich** [comment]
Oh you were faster :smile:

**Comment by ogarcia** [comment]
Yes, when I got the error I realized which dependency was missing :joy: .

**Comment by ogarcia** [comment]
@jgillich seems that 0.1.1 has a change that prevents build.
The error is:
```
# github.com/getseabird/seabird
flag provided but not defined: -Wl,--sort-common
usage: link [options] main.o
```

I am not sure how to solve it.

**Comment by jgillich** [comment]
I don't know, the build instructions in CI/Flatpak haven't changed. Go inserted a toolchain directive in go.mod, perhaps that's related

**Comment by jgillich** [comment]
Try GOTOOLCHAIN=local

**Comment by ogarcia** [comment]
The culprit is a GOFLAG. I removed them all and it compiled perfectly. Let's see if I find the wrong one. Thank you very much @jgillich !
